name: Cloud Talents Startup 

on:
  push:
    branches: [ main ]
  pull_request:

env:
  AWS_REGION: "eu-west-1"
  PACKER_VERSION: "latest"


permissions:
  contents: read
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
      
    steps:
      - name: Repositiry Checkout
        uses: actions/checkout@v4
      - name: Packer version
        uses: hashicorp/setup-packer@main
        id: setup
        with:
          version: ${{ env.PACKER_VERSION }}
        
         
      - name: Packer init
        run: terraform init -backend-config="token=${{ secrets.TFC_TOKEN }}"
         
      - name: apply
        id: init
        run: "packer init ./image.pkr.hcl"

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          audience: sts.amazonaws.com
          role-to-assume: ${{ secrets.PACKER_ROLE }}
          aws-region: ${{ secrets.REGION }}

      - name: Run "packer build"
        run: packer build -on-error=abort -var "vpc_id=${{ vars.vpc_id }}" -var "subnet_id=${{ vars.subnet_id }}" -var "version=${{ vars.version }}" ./image.pkr.hcl