name: Packer AMI Build

on:
  release:
    types: [created]

jobs:
  build-ami:
    name: Build AMI
    runs-on: ubuntu-latest

    permissions:
      id-token: write 
      contents: read

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }} 
          aws-region: ${{ secrets.AWS_REGION }} || "eu-west-2"
          
      - name: Get Release Version
        id: get_version
        run: echo "VERSION=${{ github.event.release.tag_name }}" >> $GITHUB_ENV

      - name: Setup Packer
        uses: hashicorp/setup-packer@main
        with:
          version: "latest"

      - name: Run Packer Build
        run: |
          packer build -var "app_version=${{ env.VERSION }}" .

      - name: Set AMI Name
        run: echo "AMI_NAME=cloudtalents-startup-${{ github.sha }}" >> $GITHUB_ENV
