name: packer

on:
  push:



jobs:
  packer:
    runs-on: ubuntu-latest
    name: Run Packer
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup `packer`
        uses: hashicorp/setup-packer@main
        id: setup
        with:
          version: ${{ secrets.PRODUCT_VERSION }}

      - name: Run `packer init`
        id: init
        run: "packer init ./image.pkr.hcl"

      - name: Run `packer validate`
        id: validate
        run: 
          packer validate \
            - var "subnet_id=${{ secrets.SUBNET_ID }}" \
            - var "vpc_id=${{ secrets.VPC_ID}}" \
            - var "version=${{ secrets.PRODUCT_VERSION }}"\
          ./image.pkr.hcl
  
